import { useState, useCallback, useRef } from "react";
import { useTranslation } from "react-i18next";
import "./ReportPreview.css";

interface ReportPreviewProps {
  pageSize: "A4" | "A3";
  orientation: "portrait" | "landscape";
}

const PAGE_DIMS = {
  A4: { portrait: { w: 210, h: 297 }, landscape: { w: 297, h: 210 } },
  A3: { portrait: { w: 297, h: 420 }, landscape: { w: 420, h: 297 } },
};

const SAMPLE_PAGES = [
  {
    title: "Cover",
    content: `
      <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;text-align:center;font-family:'Space Grotesk',sans-serif">
        <div style="font-size:11px;color:#D97706;letter-spacing:2px;text-transform:uppercase;margin-bottom:24px">OpenAEC Report Generator</div>
        <h1 style="font-size:28px;font-weight:700;color:#36363E;margin:0 0 8px">Sample Report</h1>
        <p style="font-size:14px;color:#71717A;margin:0 0 32px">Project Template Documentation</p>
        <div style="width:60px;height:2px;background:#D97706;margin:0 auto 32px"></div>
        <div style="font-size:11px;color:#A1A1AA">
          <p>Project: PROJ-2026-001</p>
          <p>Date: 2026-03-23</p>
          <p>Status: CONCEPT</p>
        </div>
      </div>`,
  },
  {
    title: "Content",
    content: `
      <div style="padding:20mm;font-family:'Inter',sans-serif;font-size:10px;color:#36363E;line-height:1.6">
        <h2 style="font-size:16px;font-weight:600;color:#D97706;border-bottom:1px solid #E5E7EB;padding-bottom:4px;margin:0 0 12px">1. Introduction</h2>
        <p style="margin:0 0 10px">This is a sample report generated by the OpenAEC Report Generator. It demonstrates the layout capabilities including cover pages, content sections, calculations, and tables.</p>
        <h3 style="font-size:13px;font-weight:600;color:#36363E;margin:16px 0 8px">1.1 Scope</h3>
        <p style="margin:0 0 10px">The report template supports multiple content block types: paragraphs, calculations, unity checks, tables, images, maps, and more.</p>
        <h2 style="font-size:16px;font-weight:600;color:#D97706;border-bottom:1px solid #E5E7EB;padding-bottom:4px;margin:24px 0 12px">2. Calculations</h2>
        <div style="background:#FEFCE8;border:1px solid #FDE68A;border-radius:4px;padding:10px 14px;margin:0 0 12px">
          <div style="font-weight:600;margin-bottom:4px">Bending Moment</div>
          <div style="font-family:'JetBrains Mono',monospace;font-size:9px;color:#71717A">M = q * L^2 / 8 = 5.0 * 6.0^2 / 8</div>
          <div style="font-weight:700;color:#D97706;margin-top:4px">M = 22.50 kNm</div>
        </div>
        <div style="background:#F0FDF4;border:1px solid #BBF7D0;border-radius:4px;padding:10px 14px;margin:0 0 12px">
          <div style="display:flex;justify-content:space-between;align-items:center">
            <span style="font-weight:600">Unity Check: Bending</span>
            <span style="font-weight:700;color:#16A34A">UC = 0.75 &le; 1.00 &#10003;</span>
          </div>
          <div style="background:#E5E7EB;border-radius:4px;height:6px;margin-top:6px;overflow:hidden">
            <div style="background:#16A34A;height:100%;width:75%;border-radius:4px"></div>
          </div>
        </div>
      </div>`,
  },
];

export default function ReportPreview({ pageSize, orientation }: ReportPreviewProps) {
  const { t } = useTranslation("common");
  const [zoom, setZoom] = useState(80);
  const containerRef = useRef<HTMLDivElement>(null);

  const dims = PAGE_DIMS[pageSize][orientation];
  const scale = zoom / 100;

  const handleZoomIn = useCallback(() => setZoom((z) => Math.min(300, z + 10)), []);
  const handleZoomOut = useCallback(() => setZoom((z) => Math.max(30, z - 10)), []);

  const handleWheel = useCallback((e: React.WheelEvent) => {
    if (e.ctrlKey || e.metaKey) {
      e.preventDefault();
      setZoom((z) => Math.max(30, Math.min(300, z + (e.deltaY < 0 ? 10 : -10))));
    }
  }, []);

  const handlePrint = useCallback(() => {
    const html = SAMPLE_PAGES.map((p) => p.content).join('<div style="page-break-after:always"></div>');
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>Report Preview</title>
      <style>@page{size:${pageSize} ${orientation};margin:0}body{margin:0;font-family:Inter,sans-serif}</style>
      </head><body>${html}<script>window.onload=()=>window.print()</script></body></html>`);
    win.document.close();
  }, [pageSize, orientation]);

  return (
    <div className="report-preview" onWheel={handleWheel}>
      <div className="report-toolbar">
        <span className="report-page-info">
          {SAMPLE_PAGES.length} {SAMPLE_PAGES.length === 1 ? "page" : "pages"} &middot; {pageSize} {orientation}
        </span>
        <div className="report-zoom-controls">
          <button className="report-zoom-btn" onClick={handleZoomOut} title="Zoom out">-</button>
          <span className="report-zoom-label">{zoom}%</span>
          <button className="report-zoom-btn" onClick={handleZoomIn} title="Zoom in">+</button>
        </div>
        <button className="report-print-btn" onClick={handlePrint}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="6 9 6 2 18 2 18 9" />
            <path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2" />
            <rect x="6" y="14" width="12" height="8" />
          </svg>
          {t("print")}
        </button>
      </div>
      <div className="report-pages-wrapper" ref={containerRef}>
        {SAMPLE_PAGES.map((page, i) => (
          <div
            key={i}
            className="report-page"
            style={{
              width: `${dims.w}mm`,
              height: `${dims.h}mm`,
              transform: `scale(${scale})`,
              transformOrigin: "top center",
              marginBottom: `${-dims.h * (1 - scale) + 16}px`,
            }}
          >
            <div dangerouslySetInnerHTML={{ __html: page.content }} style={{ height: "100%" }} />
          </div>
        ))}
      </div>
    </div>
  );
}
